// packages/vue-host/src/App.vue
<template>
  <Header name="Vue Host" />
  <div class="container mx-auto">
    <div class="flex w-full">
      <div class="grid grid-cols-1">
        <div class="flex justify-center">
          <BookSearch class="my-8 w-1/2" />
        </div>
        <BookList />
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import { defineComponent } from "vue";
import BookList from "remote/BookList";
import BookSearch from "remote/BookSearch";
import store from "remote/store";
import Header from "remote/Header";

export default defineComponent({
  components: {
    BookList,
    BookSearch,
    Header
  },
  computed: {
    count: {
      get() {
        return store.filteredBooks.length;
      },
      set() {},
    },
  },
});
</script>

// packages/react-host/src/App.tsx
import React, { useEffect, useRef } from "react";
import ReactDOM from "react-dom";

import "./index.scss";

import VanillaHeader from "remote/VanillaHeader";
import VanillaBookList from "remote/VanillaBookList";
import { initStore } from "remote/store";

initStore();


const App = () => {
  const headerRef = useRef();
  const booksListRef = useRef();
  useEffect(() => {
    VanillaHeader(headerRef.current, {name: 'React Host'});
    VanillaBookList(booksListRef.current);
  }, []);

  return (
    <div className="font-serif">
      <div ref={headerRef}></div>
      <div className="container mx-auto mt-4">
        <div className="flex w-full">
          <div className="grid grid-cols-1">
            <div ref={booksListRef}></div>
          </div>
        </div>
      </div>
    </div>
  );
};
ReactDOM.render(<App />, document.getElementById("app"));
